name: Java CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup local maven cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-cache-${{ hashFiles('**/pom.xml') }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 11

    - name: Build with Maven
      run: mvn -e --no-transfer-progress install
